### ISSUE TITLE
Auxiliary Ink Supplier block crashes on dedicated servers

### ISSUE THREAD

**Issue by TheWinABagel** [eehunter/Spectral-Utilities#2]
[Crash report](https://mclo.gs/ktUbWQC)
It seems that the block entity isn't being registered on servers properly (I might be wrong, I don't know kotlin)

**Comment by TheWinABagel** [comment]
It crashes (the server) when broken and when waila looks at it

**Comment by eehunter** [comment]
I'm aware of the most likely cause of this issue and have already implemented a fix on my end. Unfortunately other things have been occupying my time and pulled me away from this project before I could polish up some other new features and post the next release.

**Comment by SnowboundCabin** [comment]
Can confirm this also occurs for me, the exception for me is:
```
[21:18:39] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
        at com.oyosite.ticon.specutils.block.auxilary_ink_supplier.AuxiliaryInkSupplierBlockEntity.<init>(AuxiliaryInkSupplierBlockEntity.kt:30) ~[specutils-1.0.1.jar:?]
        at com.oyosite.ticon.specutils.block.auxilary_ink_supplier.AuxiliaryInkSupplierBlock.method_10123(AuxiliaryInkSupplierBlock.kt:37) ~[specutils-1.0.1.jar:?]
        at net.minecraft.class_2818.method_12208(class_2818.java:303) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.method_12201(class_2818.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8321(class_1937.java:559) ~[server-intermediary.jar:?]
        at mcp.mobius.waila.network.Packets.lambda$initServer$10(Packets.java:142) ~[wthit-fabric-8.13.3.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:block_entity_type / specutils:auxiliary_ink_supplier])
        at net.minecraft.class_2370.method_40274(class_2370.java:135) ~[server-intermediary.jar:?]
        at net.minecraft.class_2370.method_46744(class_2370.java:141) ~[server-intermediary.jar:?]
        at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.method_39197(class_2378.java:118) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.method_10230(class_2378.java:114) ~[server-intermediary.jar:?]
        at com.oyosite.ticon.specutils.block.BlockRegistry$BlockEntities.<clinit>(BlockRegistry.kt:31) ~[specutils-1.0.1.jar:?]
        ... 19 more
```

**Comment by eehunter** [comment]
Fixed in latest update.
